### ISSUE TITLE
Support job timeout

### ISSUE THREAD

**Issue by michaeldiamant** [mesos/chronos#186]
On several occasions, a long-running Chronos job runs indefinitely due to abnormal operating conditions.  Ideally, the job implementer takes error conditions into consideration, but this is unlikely in practice.  Given this situation, it is desirable to be able to specify a job timeout.  Two outcomes are possible:
1. If the job is still running when the timeout is reached, then the Mesos task(s) is/are killed.  If job retries remain, then the job is retried until zero retries remain, at which point, the job is marked failed.
2. If the job concludes before the timeout is reached, then the timeout does not affect the job outcome.

**Comment by elison** [comment]
Just came across this. How would you go about doing this for a docker job? If docker itself is hanging then using timeout on the job that runs in docker wouldn't work. 
Would a work around just be to schedule the docker job as a scheduled job instead of using the "container" key? What are the repercussions of running docker as a scheduled job instead of a docker job?

**Comment by timcharper** [comment]
@elison you can provide a shell script to be run in your docker container. If there is some special entrypoint script then have your provided shell script call that.

**Comment by timcharper** [comment]
@elison I think such an exception would be better detected and handled in the mesos docker containerizer itself.
