### ISSUE TITLE
Multiple instances of the same job are executing

### ISSUE THREAD

**Issue by mngo87** [mesos/chronos#411]
Chronos by default only allows one instance of a job to run at a time.  However, if the Chronos node dies or is shut down, the new Chronos node (via failover) will not know of previously running tasks.  The currently running tasks are currently being managed by the runningTasks map in MesosJobFramework.scala.  Upon startup, a Chronos node will not properly fill this runningTasks map, hence if a job is already running, another instance of that job will be scheduled.

Here is a breakdown of the reproducible steps:
1. Have a clustered chronos setup
2. Start a long running job (i.e. jobA)
3. Kill the leader Chronos node
4. jobA is still running on Mesos
5. Trigger a run on jobA
6. jobA will be scheduled again.

**Comment by elingg** [comment]
Thanks for finding this @mngo87!  I investigated further and found the issue here as TODO. The running tasks are not persisted to Zookeeper. They are only in memory when launched so reconciliation will not happen upon failover unless a task gives a status update with "running." To fix this properly would involve persisting task state into zookeeper and would be a significant PR fix. https://github.com/mesos/chronos/blob/4a7319edcda1a087b942d35c2efd753c7cea0eed/src/main/scala/org/apache/mesos/chronos/scheduler/mesos/MesosJobFramework.scala#L74-L75 Any further comments, @brndnmtthws?

**Comment by mngo87** [comment]
Thanks for the follow up @elingg .  Let me know if this is on the roadmap at some point.

**Comment by brndnmtthws** [comment]
Yep, that's correct. It does not persist the list of running jobs in a durable fashion.
